
spring.datasource.url=jdbc:postgresql://dpg-d6d9ddfpm1nc739lkrh0-a:5432/bitykart_postgres
spring.datasource.username=bitykart_postgres_user
spring.datasource.password=YYg1fxMWDEjVeGrrmkZbc4rQFIAztDBm
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}


