#spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
#spring.datasource.username=root
#spring.datasource.password=apZdUpRkYmCkCmEOCKUcWyLuvyjrRNIZ
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.datasource.url=jdbc:postgresql://dpg-d5mft2hr0fns73ev251g-a:5432/bitykart_ax5p
spring.datasource.username=bitykart_ax5p_user
spring.datasource.password=LuBqK6zNxXPdP2ss7aUUYopZk8x3tfkx
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}


